function makeSelection(x1, x2, x3, x4, y1, y2, y3, y4) {
    var idsetd = charIDToTypeID("setd");
    var desc380 = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var ref188 = new ActionReference();
    var idChnl = charIDToTypeID("Chnl");
    var idfsel = charIDToTypeID("fsel");
    ref188.putProperty(idChnl, idfsel);
    desc380.putReference(idnull, ref188);
    var idT = charIDToTypeID("T   ");
    var desc381 = new ActionDescriptor();
    var idPts = charIDToTypeID("Pts ");
    var list58 = new ActionList();
    var desc382 = new ActionDescriptor();
    var idHrzn = charIDToTypeID("Hrzn");
    var idPxl = charIDToTypeID("#Pxl");
    desc382.putUnitDouble(idHrzn, idPxl, x1);
    var idVrtc = charIDToTypeID("Vrtc");
    var idPxl = charIDToTypeID("#Pxl");
    desc382.putUnitDouble(idVrtc, idPxl, y1);
    var idPnt = charIDToTypeID("Pnt ");
    list58.putObject(idPnt, desc382);
    var desc383 = new ActionDescriptor();
    var idHrzn = charIDToTypeID("Hrzn");
    var idPxl = charIDToTypeID("#Pxl");
    desc383.putUnitDouble(idHrzn, idPxl, x2);
    var idVrtc = charIDToTypeID("Vrtc");
    var idPxl = charIDToTypeID("#Pxl");
    desc383.putUnitDouble(idVrtc, idPxl, y2);
    var idPnt = charIDToTypeID("Pnt ");
    list58.putObject(idPnt, desc383);
    var desc384 = new ActionDescriptor();
    var idHrzn = charIDToTypeID("Hrzn");
    var idPxl = charIDToTypeID("#Pxl");
    desc384.putUnitDouble(idHrzn, idPxl, x3);
    var idVrtc = charIDToTypeID("Vrtc");
    var idPxl = charIDToTypeID("#Pxl");
    desc384.putUnitDouble(idVrtc, idPxl, y3);
    var idPnt = charIDToTypeID("Pnt ");
    list58.putObject(idPnt, desc384);
    var desc385 = new ActionDescriptor();
    var idHrzn = charIDToTypeID("Hrzn");
    var idPxl = charIDToTypeID("#Pxl");
    desc385.putUnitDouble(idHrzn, idPxl, x4);
    var idVrtc = charIDToTypeID("Vrtc");
    var idPxl = charIDToTypeID("#Pxl");
    desc385.putUnitDouble(idVrtc, idPxl, y4);
    var idPnt = charIDToTypeID("Pnt ");
    list58.putObject(idPnt, desc385);
    var desc386 = new ActionDescriptor();
    var idHrzn = charIDToTypeID("Hrzn");
    var idPxl = charIDToTypeID("#Pxl");
    desc386.putUnitDouble(idHrzn, idPxl, x1);
    var idVrtc = charIDToTypeID("Vrtc");
    var idPxl = charIDToTypeID("#Pxl");
    desc386.putUnitDouble(idVrtc, idPxl, y1);
    var idPnt = charIDToTypeID("Pnt ");
    list58.putObject(idPnt, desc386);
    desc381.putList(idPts, list58);
    var idPlgn = charIDToTypeID("Plgn");
    desc380.putObject(idT, idPlgn, desc381);
    var idAntA = charIDToTypeID("AntA");
    desc380.putBoolean(idAntA, true);
    executeAction(idsetd, desc380, DialogModes.NO);
}